=== Jochannes/MolSim/src/XMLInput/simulation.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:simpleType name="simulation-mode-type_t">
    <xs:restriction base="xs:string">
      <xs:enumeration value="normal"/>
      <xs:enumeration value="linked-cell"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="boundary-type_t">
    <xs:restriction base="xs:string">
      <xs:enumeration value="outflow"/>
      <xs:enumeration value="reflect"/>
      <xs:enumeration value="periodic"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="boundary_t">
    <xs:attribute name="x_0" type="boundary-type_t" use="required"/>
    <xs:attribute name="x_max" type="boundary-type_t" use="required"/>
    <xs:attribute name="y_0" type="boundary-type_t" use="required"/>
    <xs:attribute name="y_max" type="boundary-type_t" use="required"/>
    <xs:attribute name="z_0" type="boundary-type_t" use="required"/>
    <xs:attribute name="z_max" type="boundary-type_t" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="simulation_force-calculator_t">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="lennard-jones" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="lj-cutoff" type="lj_cutoff_t"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="gravity" type="gravity_t"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="lj_cutoff_t">
  	<xs:attribute name="cutoff_factor" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="gravity_t">
  	<xs:attribute name="g_grav" type="xs:double" use="required"/>
  </xs:complexType>
  
  
  <xs:complexType name="simulation-mode_t">
    <xs:sequence>
      <xs:element name="type" type="simulation-mode-type_t"/>
      <xs:element minOccurs="0" name="cutoff_radius" type="xs:double"/>
      <xs:element minOccurs="0" name="domain_size_x" type="xs:double"/>
      <xs:element minOccurs="0" name="domain_size_y" type="xs:double"/>
      <xs:element minOccurs="0" name="domain_size_z" type="xs:double"/>
      <xs:element minOccurs="0" name="boundary" type="boundary_t"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="simulation_parameters_t">
    <xs:sequence>
      <xs:element name="start-time" type="xs:double"/>
      <xs:element name="end-time" type="xs:double"/>
      <xs:element name="delta-t" type="xs:double"/>
      <xs:element name="simulation-mode" type="simulation-mode_t"/>
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="cuboid_t">
    <xs:attribute name="x1" type="xs:double" use="required"/>
    <xs:attribute name="x2" type="xs:double" use="required"/>
    <xs:attribute name="x3" type="xs:double" use="required"/>
    <xs:attribute name="n1" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="n2" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="n3" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="h" type="xs:double" use="required"/>
    <xs:attribute name="m" type="xs:double" use="required"/>
    <xs:attribute name="epsilon" type="xs:double" use="required"/>
    <xs:attribute name="sigma" type="xs:double" use="required"/>
    <xs:attribute name="type" type="xs:int" use="required"/>
    <xs:attribute name="v1" type="xs:double" use="required"/>
    <xs:attribute name="v2" type="xs:double" use="required"/>
    <xs:attribute name="v3" type="xs:double" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="sphere_t">
    <xs:attribute name="x1" type="xs:double" use="required"/>
    <xs:attribute name="x2" type="xs:double" use="required"/>
    <xs:attribute name="x3" type="xs:double" use="required"/>
    <xs:attribute name="r" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="h" type="xs:double" use="required"/>
    <xs:attribute name="m" type="xs:double" use="required"/>
    <xs:attribute name="epsilon" type="xs:double" use="required"/>
    <xs:attribute name="sigma" type="xs:double" use="required"/>
    <xs:attribute name="type" type="xs:int" use="required"/>
    <xs:attribute name="v1" type="xs:double" use="required"/>
    <xs:attribute name="v2" type="xs:double" use="required"/>
    <xs:attribute name="v3" type="xs:double" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="simulation_input_t">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="particle_file" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="cuboid" type="cuboid_t"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="sphere" type="sphere_t"/>
    </xs:sequence>
  </xs:complexType>
  

  <xs:complexType name="simulation_output_t">
    <xs:sequence>
      <xs:element name="base_filename" type="xs:string"/>
      <xs:element name="output_freq" type="xs:unsignedInt"/>
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="simulation_t">
    <xs:sequence>
      <xs:element name="parameter" type="simulation_parameters_t"/>
      <xs:element name="force-calculator" type="simulation_force-calculator_t"/>
      <xs:element name="input" type="simulation_input_t"/>
      <xs:element name="output" type="simulation_output_t"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="simulation" type="simulation_t"/>


</xs:schema>

=== Jochannes/MolSim/examples/sheet2_run1.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>5</end-time>
    <delta-t>0.0002</delta-t>
    
    <force-calculator>
      <type>lennard-jones</type>
      <epsilon>5</epsilon>
      <sigma>1</sigma>
    </force-calculator>
    
    <simulation-mode>
      <type>normal</type>
    </simulation-mode>
  </parameter>
  
  
  <input>
    <cuboid_file>examples/eingabe-cuboid1.txt</cuboid_file>
  </input>
  
  
  <output>
    <base_filename>MD_vtk</base_filename>
    <output_freq>10</output_freq>
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/example.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>20</end-time>
    <delta-t>0.0005</delta-t>
    
    <force-calculator>
      <type>lennard-jones</type>
      <epsilon>5</epsilon>
      <sigma>1</sigma>
    </force-calculator>
    
    <simulation-mode>
      <type>linked-cell</type>
      <cutoff_radius>3</cutoff_radius>
      <domain_size_x>180</domain_size_x>
      <domain_size_y>90</domain_size_y>
    </simulation-mode>
  </parameter>
  
  
  <input>
    <particle_file>example_particle_file.txt</particle_file>
    <cuboid_file>example_cuboid_file.txt</cuboid_file>
    <sphere_file>example_sphere_file.txt</sphere_file>
  </input>
  
  
  <output>
    <base_filename>MD_vtk</base_filename>
    <output_freq>10</output_freq>
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/sheet4_ex2_run1.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>25</end-time>
    <delta-t>0.0005</delta-t>
    
    <simulation-mode>
      <type>linked-cell</type>
      <cutoff_radius>2.5</cutoff_radius>
      <domain_size_x>63</domain_size_x>
      <domain_size_y>36</domain_size_y>
      <boundary x_0="periodic" x_max="periodic" y_0="reflect" y_max="outflow" z_0="outflow" z_max="outflow" />
    </simulation-mode>
    
    <thermostat dim="2" steps="1000" init_temp="40" />
  </parameter>
  
  <force-calculator>
    <lennard-jones cutoff_factor="2.5" />
    <gravity g_grav="-12.44" />
  </force-calculator>
  
  <input>
    <cuboid x1="0.6" x2="2.0" x3="0.0" n1="50" n2="14" n3="1" h="1.2" m="1.0" epsilon="1.0" sigma="1.0" type="1" v1="0.0" v2="0.0" v3="0.0" />
    <cuboid x1="0.6" x2="19.0" x3="0.0" n1="50" n2="14" n3="1" h="1.2" m="2.0" epsilon="1.0" sigma="0.9412" type="2" v1="0.0" v2="0.0" v3="0.0" />
  </input>
  
  
  <output>
    <iteration base_filename="Output/sheet4_ex2_run1/MD_vtk" output_freq="100" />
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/sheet5_ex5_run1.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>150</end-time>
    <delta-t>0.001</delta-t>
    
    <simulation-mode>
      <type>linked-cell</type>
      <cutoff_radius>2.3</cutoff_radius>
      <domain_size_x>9.2</domain_size_x>
      <domain_size_y>9.2</domain_size_y>
      <domain_size_z>9.2</domain_size_z>
      <boundary x_0="periodic" x_max="periodic" y_0="periodic" y_max="periodic" z_0="periodic" z_max="periodic" />
    </simulation-mode>
    
    <thermostat dim="3" steps="40" init_temp="0.01" target_temp="3.0" delta_temp="0.001" steps_changetemp="40" apply_brown="true" />
  </parameter>
  
  <force-calculator>
    <lj-smoothed cutoff_factor="2.3" rl="1.9" />
  </force-calculator>
  
  <input>
    <cuboid x1="0.575" x2="0.575" x3="0.575" n1="8" n2="8" n3="8" h="1.15" m="1.0" epsilon="1.0" sigma="1.0" type="1" v1="0.0" v2="0.0" v3="0.0" />
  </input>
  
  
  <output>
    <iteration base_filename="Output/sheet5_ex5_run1/MD_vtk" output_freq="100" />
    <result filename="examples/sheet5_ex5_run1_result.txt" />
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/sheet3_run2.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>10</end-time>
    <delta-t>0.00005</delta-t>
    
    <force-calculator>
      <type>lennard-jones</type>
      <epsilon>5</epsilon>
      <sigma>1</sigma>
    </force-calculator>
    
    <simulation-mode>
      <type>linked-cell</type>
      <cutoff_radius>3</cutoff_radius>
      <domain_size_x>120</domain_size_x>
      <domain_size_y>50</domain_size_y>
      <boundary x_0="reflect" x_max="reflect" y_0="reflect" y_max="reflect" z_0="reflect" z_max="reflect" />
    </simulation-mode>
  </parameter>
  
  
  <input>
    <sphere x1="60.0" x2="25.0" x3="0.0" r="15" h="1.1225" m="1.0" v1="0.0" v2="-10.0" v3="0.0" />
  </input>
  
  
  <output>
    <base_filename>Output/MD_vtk</base_filename>
    <output_freq>100</output_freq>
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/sheet3_run1_new.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>20</end-time>
    <delta-t>0.0005</delta-t>
    
    <simulation-mode>
      <type>linked-cell</type>
      <cutoff_radius>3</cutoff_radius>
      <domain_size_x>180</domain_size_x>
      <domain_size_y>90</domain_size_y>
    </simulation-mode>
  </parameter>
  
  <force-calculator>
    <lj-cutoff cutoff_factor="3.0" />
  </force-calculator>
  
  <input>
    <cuboid x1="20.0" x2="20.0" x3="0.0" n1="100" n2="20" n3="1" h="1.1225" m="1.0" epsilon="5.0" sigma="1.0" type ="1" v1="0.0" v2="0.0" v3="0.0" />
    <cuboid x1="70.0" x2="60.0" x3="0.0" n1="20" n2="20" n3="1" h="1.1225" m="1.0" epsilon="5.0" sigma="1.0" type ="2" v1="0.0" v2="-10.0" v3="0.0" />
  </input>
  
  
  <output>
    <base_filename>Output/MD_vtk</base_filename>
    <output_freq>10</output_freq>
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/sheet5_ex1.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>500</end-time>
    <delta-t>0.01</delta-t>
    
    <simulation-mode>
      <type>membrane</type>
      <cutoff_radius>4.0</cutoff_radius>
      <domain_size_x>148</domain_size_x>
      <domain_size_y>148</domain_size_y>
      <domain_size_z>148</domain_size_z>
      <boundary x_0="reflect" x_max="reflect" y_0="reflect" y_max="reflect" z_0="reflect" z_max="reflect" />
    </simulation-mode>
    
  </parameter>
  
  <force-calculator>
    <lennard-jones cutoff_factor="1.12246204831" />
    <gravity g_grav="-0.001" direction="z" />
    <harmonic k="300" r="2.2" />
    <constant type="2" force_x="0" force_y="0" force_z="0.8" end_time="150" />
  </force-calculator>
  
  <input>
    <membrane x1="15" x2="15" x3="1.5" n1="50" n2="50" n3="1" h="2.2" m="1.0" epsilon="1.0" sigma="1.0" type="1" v1="0.0" v2="0.0" v3="0.0" mark_type="2" mark_x="17" mark_y="24" />
  </input>
  
  
  <output>
    <iteration base_filename="Output/sheet5_ex1/MD_vtk" output_freq="1" />
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/sheet5_ex4.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>500</end-time>
    <delta-t>0.0005</delta-t>
    
    <simulation-mode>
      <type>linked-cell</type>
      <cutoff_radius>2.75</cutoff_radius>
      <domain_size_x>35</domain_size_x>
      <domain_size_y>25</domain_size_y>
      <domain_size_z>10</domain_size_z>
      <boundary x_0="periodic" x_max="periodic" y_0="periodic" y_max="periodic" z_0="periodic" z_max="periodic" />
    </simulation-mode>
    
    <thermostat dim="3" steps="10" init_temp="40" type="2" direction="1" />
    
    <fixed>0 1</fixed>
    
    <velocity-density-profile x_start="0.0" x_end="30.0" x_count="50" file="veldenprof.csv" freq="10000" />
  </parameter>
  
  <force-calculator>
    <lennard-jones cutoff_factor="2.5" />
    <gravity g_grav="-0.8" type="2"/>
  </force-calculator>
  
  <input>
    <cuboid x1="1.0" x2="0.6" x3="0.6" n1="2" n2="23" n3="9" h="1.12" m="1.0" epsilon="2.0" sigma="1.1" type="0" v1="0.0" v2="0.0" v3="0.0" />
    <cuboid x1="27.4" x2="0.6" x3="0.6" n1="2" n2="23" n3="9" h="1.12" m="1.0" epsilon="2.0" sigma="1.1" type="1" v1="0.0" v2="0.0" v3="0.0" />
    <cuboid x1="3.4" x2="0.6" x3="0.6" n1="20" n2="21" n3="8" h="1.2" m="1.0" epsilon="1.0" sigma="1.0" type="2" v1="0.0" v2="0.0" v3="0.0" />
  </input>
  
  
  <output>
    <iteration base_filename="Output/sheet5_ex4/MD_vtk" output_freq="100" />
  </output>
  
  
</simulation>
