=== Jochannes/MolSim/src/XMLInput/simulation.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:simpleType name="simulation-mode-type_t">
    <xs:restriction base="xs:string">
      <xs:enumeration value="normal"/>
      <xs:enumeration value="linked-cell"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="boundary-type_t">
    <xs:restriction base="xs:string">
      <xs:enumeration value="outflow"/>
      <xs:enumeration value="reflect"/>
      <xs:enumeration value="periodic"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="boundary_t">
    <xs:attribute name="x_0" type="boundary-type_t" use="required"/>
    <xs:attribute name="x_max" type="boundary-type_t" use="required"/>
    <xs:attribute name="y_0" type="boundary-type_t" use="required"/>
    <xs:attribute name="y_max" type="boundary-type_t" use="required"/>
    <xs:attribute name="z_0" type="boundary-type_t" use="required"/>
    <xs:attribute name="z_max" type="boundary-type_t" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="simulation_force-calculator_t">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="lennard-jones" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="lj-cutoff" type="lj_cutoff_t"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="gravity" type="gravity_t"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="lj_cutoff_t">
  	<xs:attribute name="cutoff_factor" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="gravity_t">
  	<xs:attribute name="g_grav" type="xs:double" use="required"/>
  </xs:complexType>
  
  
  <xs:complexType name="simulation-mode_t">
    <xs:sequence>
      <xs:element name="type" type="simulation-mode-type_t"/>
      <xs:element minOccurs="0" name="cutoff_radius" type="xs:double"/>
      <xs:element minOccurs="0" name="domain_size_x" type="xs:double"/>
      <xs:element minOccurs="0" name="domain_size_y" type="xs:double"/>
      <xs:element minOccurs="0" name="domain_size_z" type="xs:double"/>
      <xs:element minOccurs="0" name="boundary" type="boundary_t"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="simulation_parameters_t">
    <xs:sequence>
      <xs:element name="start-time" type="xs:double"/>
      <xs:element name="end-time" type="xs:double"/>
      <xs:element name="delta-t" type="xs:double"/>
      <xs:element name="simulation-mode" type="simulation-mode_t"/>
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="cuboid_t">
    <xs:attribute name="x1" type="xs:double" use="required"/>
    <xs:attribute name="x2" type="xs:double" use="required"/>
    <xs:attribute name="x3" type="xs:double" use="required"/>
    <xs:attribute name="n1" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="n2" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="n3" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="h" type="xs:double" use="required"/>
    <xs:attribute name="m" type="xs:double" use="required"/>
    <xs:attribute name="epsilon" type="xs:double" use="required"/>
    <xs:attribute name="sigma" type="xs:double" use="required"/>
    <xs:attribute name="type" type="xs:int" use="required"/>
    <xs:attribute name="v1" type="xs:double" use="required"/>
    <xs:attribute name="v2" type="xs:double" use="required"/>
    <xs:attribute name="v3" type="xs:double" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="sphere_t">
    <xs:attribute name="x1" type="xs:double" use="required"/>
    <xs:attribute name="x2" type="xs:double" use="required"/>
    <xs:attribute name="x3" type="xs:double" use="required"/>
    <xs:attribute name="r" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="h" type="xs:double" use="required"/>
    <xs:attribute name="m" type="xs:double" use="required"/>
    <xs:attribute name="epsilon" type="xs:double" use="required"/>
    <xs:attribute name="sigma" type="xs:double" use="required"/>
    <xs:attribute name="type" type="xs:int" use="required"/>
    <xs:attribute name="v1" type="xs:double" use="required"/>
    <xs:attribute name="v2" type="xs:double" use="required"/>
    <xs:attribute name="v3" type="xs:double" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="simulation_input_t">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="particle_file" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="cuboid" type="cuboid_t"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="sphere" type="sphere_t"/>
    </xs:sequence>
  </xs:complexType>
  

  <xs:complexType name="simulation_output_t">
    <xs:sequence>
      <xs:element name="base_filename" type="xs:string"/>
      <xs:element name="output_freq" type="xs:unsignedInt"/>
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="simulation_t">
    <xs:sequence>
      <xs:element name="parameter" type="simulation_parameters_t"/>
      <xs:element name="force-calculator" type="simulation_force-calculator_t"/>
      <xs:element name="input" type="simulation_input_t"/>
      <xs:element name="output" type="simulation_output_t"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="simulation" type="simulation_t"/>


</xs:schema>

=== Jochannes/MolSim/examples/sheet5_ex5_run2.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>250</end-time>
    <delta-t>0.001</delta-t>
    
    <simulation-mode>
      <type>linked-cell</type>
      <cutoff_radius>2.3</cutoff_radius>
      <domain_size_x>9.2</domain_size_x>
      <domain_size_y>9.2</domain_size_y>
      <domain_size_z>9.2</domain_size_z>
      <boundary x_0="periodic" x_max="periodic" y_0="periodic" y_max="periodic" z_0="periodic" z_max="periodic" />
    </simulation-mode>
    
    <thermostat dim="3" steps="50" init_temp="3.0" target_temp="0.5" delta_temp="0.00078" steps_changetemp="50" apply_brown="false" />
    
    <thermodyn-stats freq="1000" avgover="5" dr="0.05" maxrad="2.3" varfile="Output/sheet5_ex5_run2/VarStats.csv" rdffile="Output/sheet5_ex5_run2/RDFStats.csv" />
  </parameter>
  
  <force-calculator>
    <lj-smoothed cutoff_factor="2.3" rl="1.9" />
  </force-calculator>
  
  <input>
    <particle_file>examples/sheet5_ex5_run1_result.txt</particle_file>
  </input>
  
  
  <output>
    <iteration base_filename="Output/sheet5_ex5_run2/MD_vtk" output_freq="100" />
  </output>
  
  
</simulation>

=== Jochannes/MolSim/examples/sheet1_run1.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/XMLInput/simulation.xsd">


  <parameter>
    <start-time>0</start-time>
    <end-time>1000</end-time>
    <delta-t>0.014</delta-t>
    
    <force-calculator>
      <type>gravity</type>
    </force-calculator>
    
    <simulation-mode>
      <type>normal</type>
    </simulation-mode>
  </parameter>
  
  
  <input>
    <particle_file>examples/eingabe-sonne.txt</particle_file>
  </input>
  
  
  <output>
    <base_filename>Output/MD_vtk</base_filename>
    <output_freq>10</output_freq>
  </output>
  
  
</simulation>
